import type { MetadataRoute } from "next";
import { calculators } from "@/lib/calculators";
import { toAbsoluteUrl } from "@/lib/site";

const staticRoutes = [
  "",
  "/tools",
  "/calculators",
  "/categories",
  "/guides",
  "/converters",
  "/pdf-tools",
  "/pdf-tools/category",
  "/pdf-compression-guide",
  "/jpg-to-pdf-guide",
  "/merge-pdf-guide",
  "/png-to-pdf-guide",
  "/split-pdf-guide",
  "/pdf-to-word-guide",
  "/image-to-pdf-guide",
  "/about",
  "/contact",
  "/privacy-policy",
  "/terms",
  "/disclaimer",
  "/education",
  "/how-to-calculate-gpa",
  "/weighted-vs-unweighted-gpa",
  "/how-to-improve-your-gpa",
  "/college-gpa-guide",
  "/final-grade-calculator-guide",
  "/study-time-calculator-guide",
  "/common-study-mistakes",
  "/how-many-hours-should-i-study",
  "/health",
  "/how-many-calories-should-i-eat",
  "/what-is-bmr",
  "/bmi-vs-body-fat-percentage",
  "/healthy-weight-guide",
  "/common-weight-loss-mistakes",
  "/mortgage",
  "/how-much-house-can-i-afford",
  "/fixed-vs-adjustable-rate-mortgage",
  "/mortgage-points-explained",
  "/mortgage-preapproval-guide",
  "/common-home-buying-mistakes",
  "/down-payment-guide",
  "/mortgage-closing-costs-explained",
  "/refinance-vs-new-mortgage",
  "/retirement",
  "/how-much-do-i-need-to-retire",
  "/401k-vs-ira",
  "/roth-ira-vs-traditional-ira",
  "/retirement-savings-by-age",
  "/common-retirement-planning-mistakes",
  "/how-much-should-i-save-for-retirement",
  "/retirement-income-planning",
  "/safe-withdrawal-rate-explained",
  "/tax",
  "/how-to-calculate-federal-income-tax",
  "/federal-income-tax-brackets",
  "/taxable-income-vs-gross-income",
  "/common-tax-filing-mistakes",
  "/what-is-adjusted-gross-income",
  "/tax-refund-calculator-guide",
  "/self-employment-tax-guide",
  "/zakat",
  "/hijri-to-gregorian",
  "/gregorian-to-hijri",
  "/how-to-calculate-zakat",
  "/zakat-on-business-assets",
  "/zakat-on-stocks-and-etfs",
  "/what-is-nisab",
  "/common-zakat-mistakes",
  "/zakat-calculator-usa",
  "/zakat-on-retirement-accounts",
  "/zakat-on-gold-and-silver",
];

export default function sitemap(): MetadataRoute.Sitemap {
  const calculatorRoutes = calculators.map(
    (calculator) => `/calculators/${calculator.slug}`,
  );

  return [...staticRoutes, ...calculatorRoutes].map((route) => ({
    url: toAbsoluteUrl(route || "/"),
    lastModified: new Date(),
  }));
}
